name: uza_
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #Utilities packages 
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0

  #Icons 
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management 
  get: ^4.6.5
  get_storage: ^2.1.1
  

  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  u_credit_card: ^1.1.0
  

flutter:
  uses-material-design: true

  #-----------LOCAL ASSETS ----------#

  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/on_boarding_images/
    - assets/images/banners/
    - assets/images/product_images/
 
  
